Feature/webhook
desenvolvendo-me/lead-score pull request #41
Opened 2024-06-28 20:56 UTC by Dev-LucasNunes

Tarefa: Implementar a função para receber as respostas da pesquisa  #40 

Usando o site https://www.make.com/en para receber a request

https://github.com/desenvolvendo-me/lead-score/assets/115117571/a4c4a855-b333-48bc-ac2c-83ab2d505e2a

Testes Rspec:
![Captura de tela de 2024-06-28 16-31-58](https://github.com/desenvolvendo-me/lead-score/assets/115117571/13635033-a495-418e-b94a-922c332d8f06)

2024-06-29 14:22 UTC, Pjmaciel requested changes
Verifique as mudanças propostas.

2024-06-29 14:22 UTC, Pjmaciel commented on app/helpers/webhooks_helper.rb
Não foi implementado metodos auxiliares, está correto?  Existe alguma intenção de usar, caso não,  ele pode ser removido por enquanto para manter o código mais limpo e organizado

2024-06-29 14:22 UTC, Pjmaciel commented on app/views/webhooks/receive.html.erb
Contém apenas o conteúdo padrão gerado pelo Rails,  há algum plano específico para essa view ? Remover caso não esteja sendo utilizada, para manter o projeto mais organizado.

2024-06-29 14:22 UTC, Pjmaciel commented on spec/controllers/webhooks/webhooks_controller_spec.rb
Remover comentarios.

2024-06-29 14:22 UTC, Pjmaciel commented on spec/helpers/webhooks_helper_spec.rb
Remover comentarios e substitua o pending por testes reais que validem os métodos do helper.

2024-06-29 14:22 UTC, Pjmaciel commented on spec/requests/webhooks_spec.rb
Adicionar Testes para Cenários Diferentes: Além de verificar o status HTTP, verifique se o conteúdo da resposta está correto.

2024-06-29 14:22 UTC, Pjmaciel commented on spec/views/webhooks/receive.html.railsui_spec.rb
Não entendi ao certo esse teste da view. Remover caso não esteja sendo utilizada, para manter o projeto mais organizado.

2024-06-29 21:33 UTC, marcodotcastro requested changes

2024-06-29 21:33 UTC, marcodotcastro commented on app/controllers/webhooks/webhooks_controller.rb
> +            Rails.logger.error "Missing required fields: #{missing_fields.join(', ')}"
Remova esses logger do código

2024-06-29 21:33 UTC, marcodotcastro commented on app/controllers/webhooks/webhooks_controller.rb
> +          if missing_required_fields?(data)
Remova esses regras de validação. Ainda não foi solicitado, mas se foi pedido em algum momento. Vamos pensar nisso no futuro. 

Nesse momento vamos imaginar os usuários vão fazer certo.

2024-07-01 12:43 UTC, Dev-LucasNunes commented on app/views/webhooks/receive.html.erb
Vou retirar também por enquanto, é o mesmo caso do helper, foi criado automaticamente, por enquanto  eu ainda não criei view

2024-07-01 12:51 UTC, Dev-LucasNunes commented on spec/helpers/webhooks_helper_spec.rb
Removi o arquivo, pois não tinha criado nenhum helper ainda

2024-07-01 13:06 UTC, Dev-LucasNunes commented on spec/requests/webhooks_spec.rb
Arquivo tinha sido criado automaticamente com esse teste para GET, modifiquei coloquei testes para post que é o que o webhook faz no momento

2024-07-01 13:07 UTC, Dev-LucasNunes commented on spec/views/webhooks/receive.html.railsui_spec.rb
criado automaticamente, view não é usada por enquanto, removi o arquivo de teste

2024-07-01 13:33 UTC, Dev-LucasNunes commented on app/controllers/webhooks/webhooks_controller.rb
> +            Rails.logger.error "Missing required fields: #{missing_fields.join(', ')}"
removido

2024-07-01 13:36 UTC, Dev-LucasNunes commented on app/controllers/webhooks/webhooks_controller.rb
> +          if missing_required_fields?(data)
ok, removidas as validações, só vou deixar as validações básicas

2024-07-01 18:46 UTC, marcodotcastro approved these changes

2024-07-01 18:59 UTC, Pjmaciel approved these changes
Nenhuma mudança adicional, parabéns pelo esforço!

2024-07-02 21:17 UTC, merged