visualizar lista de score
desenvolvendo-me/lead-score pull request #44
Opened 2024-07-04 00:13 UTC by alinecintracamargo

PR Referente a

#27

2024-07-04 13:03 UTC, Pjmaciel approved these changes
Verifique as mudanças propostas.

2024-07-04 13:03 UTC, Pjmaciel commented on app/models/list.rb
Eu não vi o model sendo chamado no controller no codigo, ele tem uma funcão especifica?

2024-07-05 12:56 UTC, mosca06 commented on .tool-versions
teste de resposta

2024-07-08 13:30 UTC, marcodotcastro commented on app/controllers/scores_controller.rb
Verifique como foi feito o GoalsController que é a funcionalidade de exemplo e siga o mesmo padrão

2024-07-08 13:33 UTC, marcodotcastro commented on config/routes.rb
> +  resources :scores, only: [:index, :show]
Verifique como foi feito o GoalsController que é a funcionalidade de exemplo e siga o mesmo padrão

2024-07-09 13:10 UTC, alinecintracamargo commented on config/routes.rb
> +  resources :scores, only: [:index, :show]
Feito conforme solicitado.

2024-07-09 17:41 UTC, marcodotcastro commented on app/controllers/scores_controller.rb
> +class ScoresController < ApplicationController
Use o GoalsController como referência e ajuste o ScoresController

2024-07-09 17:44 UTC, marcodotcastro commented on db/migrate/20240702120757_create_lists.rb
> +    create_table :lists do |t|
Crie um nome mais coerente para tabela

2024-07-09 17:44 UTC, marcodotcastro commented on spec/factories/lists.rb
> +    score { 1 }
Use dados próximos do real

2024-07-09 17:45 UTC, marcodotcastro commented on app/views/manager/scores/index.html.erb
> +         ].each do |person| %>
Faças as informações virem do banco de dados

2024-07-09 20:37 UTC, marcodotcastro requested changes
Veja os comentários

2024-07-09 22:36 UTC, alinecintracamargo commented on app/controllers/scores_controller.rb
Mudança realizada

2024-07-09 22:36 UTC, alinecintracamargo commented on app/controllers/scores_controller.rb
> +class ScoresController < ApplicationController
Realizado conforme orientação

2024-07-09 22:37 UTC, alinecintracamargo commented on config/routes.rb
> +      end
Modificado a forma que estava a rota.

2024-07-09 22:39 UTC, alinecintracamargo commented on app/views/manager/scores/index.html.erb
> +         ].each do |person| %>
Mudanças feitas

2024-07-10 00:15 UTC, Pjmaciel requested changes
Verifique as mudanças propostas.

2024-07-10 00:15 UTC, Pjmaciel commented on app/models/score.rb
Remova os comentários.

2024-07-10 00:15 UTC, Pjmaciel commented on app/views/manager/scores/index.html.erb
Remova os comentarios.

2024-07-10 00:15 UTC, Pjmaciel commented on spec/controllers/manager/scores_controller_spec.rb
Remova os comentários.

2024-07-10 00:15 UTC, Pjmaciel commented on spec/models/score_spec.rb
Realize os testes do model.

2024-07-10 14:09 UTC, marcodotcastro approved these changes

2024-07-10 14:13 UTC, marcodotcastro requested changes
Para finalizar:
- [x] Adicione ao seeds informações para facilitar o teste
- [ ] Adicione um pequeno video com teste final

2024-07-10 20:59 UTC, Pjmaciel approved these changes

2024-07-12 13:19 UTC, Pjmaciel approved these changes
Parabéns pelo trabalho.

2024-07-12 13:27 UTC, merged