Feature/43 token validation
desenvolvendo-me/lead-score pull request #51
Opened 2024-07-08 22:24 UTC by Dev-LucasNunes

PR referente a issue #43 
- Gerador de Token implementado, cria e atualiza no banco de dados conforme é gerado
- view do gerador de token implementada e views/manager/tokens
- opção de ir para pagina do gerador de token colocado na view _nav_menu
- teste com make e postman com token funcionando

2024-07-09 17:53 UTC, marcodotcastro commented on app/controllers/manager/tokens_controller.rb
> +  class TokensController < ApplicationController
Use o GoalsController como referencia para seguir a implementação

2024-07-09 17:56 UTC, marcodotcastro commented on app/models/user.rb
Crie uma entidade api_token vinculando ao user e client

2024-07-09 17:59 UTC, Pjmaciel requested changes
Verifique as mudanças propostas.

2024-07-09 17:59 UTC, Pjmaciel commented on app/assets/config/manifest.js
Retirar essa linha não causa nenhum problema ao RailsUI?

2024-07-09 17:59 UTC, Pjmaciel commented on app/views/layouts/application.html.erb
Houve algum problema ou conflito específico que levou à remoção do Turbo?
essa linha trabalha diretamente com o hotwire no railsUI, retirando ela pode ocorrer alguma incompatibilidade de tags.

2024-07-09 17:59 UTC, Pjmaciel commented on app/views/manager/tokens/index.html.erb
Remova os comentarios

2024-07-09 20:37 UTC, marcodotcastro requested changes
Veja os comentários

2024-07-10 13:02 UTC, Dev-LucasNunes commented on app/assets/config/manifest.js
Eu sinceramente não sei, provavelmente, eu não tinha nem entrado nesse arquivo, e nem deletado essa linha, não sei porque ela sumiu, mas ja coloquei ela de volta igual estava

2024-07-10 13:36 UTC, Dev-LucasNunes commented on app/views/layouts/application.html.erb
Outra vez, eu não faço ideia do porque essa linha sumiu, eu nem abri esse application, tenho certeza que é uma linha importante,  já retornei a linha

2024-07-10 13:40 UTC, Dev-LucasNunes commented on app/helpers/users/tokens_helper.rb
Removido

2024-07-11 17:15 UTC, Dev-LucasNunes commented on app/models/user.rb
Alterações feitas, vinculo feito entre entidade criada api_token com User e Client

2024-07-11 17:16 UTC, Dev-LucasNunes commented on app/controllers/manager/tokens_controller.rb
> +  class TokensController < ApplicationController
Alteração feita usando Goal_contoller como referencia

2024-07-12 13:15 UTC, Pjmaciel requested changes
Verifique os comentarios.

2024-07-12 13:15 UTC, Pjmaciel commented on spec/requests/manager/tokens_spec.rb
Retire o comentario.

2024-07-12 22:36 UTC, Pjmaciel approved these changes

2024-07-18 12:06 UTC, marcodotcastro approved these changes

2024-07-18 20:18 UTC, merged