Feature/22 configurar recebimento dos dados utilizando tabelas
desenvolvendo-me/lead-score pull request #52
Opened 2024-07-08 23:43 UTC by mosca06

- [ ] #22

2024-07-09 17:40 UTC, Pjmaciel requested changes
Realize as modificaçoes propostas.

2024-07-09 17:40 UTC, Pjmaciel commented on spec/models/answer_table_spec.rb
Falta a implementação do teste, esta com o codigo gerado automatico do rspec.

2024-07-09 17:47 UTC, marcodotcastro commented on app/businesses/data_processing/score_calculator.rb
> +      answers_weights = WeightTable.take.question_answer
Remover o nome table da entidade model

2024-07-09 17:50 UTC, marcodotcastro commented on app/businesses/data_processing/score_calculator.rb
>  module DataProcessing
O modulo por ser chamado de Score e a classe Calculator

2024-07-09 17:52 UTC, marcodotcastro commented on app/businesses/data_processing/score_calculator.rb
> +      answers_weights = WeightTable.take.question_answer
Não busque as informações do banco de dados, receba as informações para processar. Assim remove a dependência.

2024-07-09 17:52 UTC, marcodotcastro commented on spec/businesses/data_processing/score_calculator_spec.rb
Não use teste mock

2024-07-09 20:37 UTC, marcodotcastro requested changes
Veja os comentários

2024-07-09 22:19 UTC, mosca06 commented on spec/models/answer_table_spec.rb
teste implementado

2024-07-09 22:19 UTC, mosca06 commented on app/businesses/data_processing/score_calculator.rb
> +      answers_weights = WeightTable.take.question_answer
removido nome  table nas entidades

2024-07-09 22:20 UTC, mosca06 commented on app/businesses/data_processing/score_calculator.rb
>  module DataProcessing
modulo e classe alterados com os nomes propostos

2024-07-09 22:20 UTC, mosca06 commented on app/businesses/data_processing/score_calculator.rb
> +      answers_weights = WeightTable.take.question_answer
funçao voltou a receber por paramentros e recebendo eles pelos testes

2024-07-09 22:21 UTC, mosca06 commented on spec/businesses/data_processing/score_calculator_spec.rb
acredito ter tirado o mock

2024-07-09 22:53 UTC, marcodotcastro commented on app/businesses/score/calculator.rb
> +      lead_answers = json_lead_answers["answers"]
Receba somente os jsons. Você vai receber json answers e json weights.

2024-07-09 22:55 UTC, marcodotcastro requested changes
Veja os comentários

2024-07-09 23:28 UTC, mosca06 commented on app/businesses/score/calculator.rb
> +      lead_answers = json_lead_answers["answers"]
atualizado funçao e testes para receber apenas os jsons

2024-07-10 00:09 UTC, Pjmaciel approved these changes

2024-07-12 13:11 UTC, Pjmaciel approved these changes

2024-07-12 13:11 UTC, merged