Feature/12 validacao de perguntas e respostas
desenvolvendo-me/lead-score pull request #53
Opened 2024-07-09 15:03 UTC by ReginaTR

PR referente a validação das perguntas, resposta e peso.

2024-07-09 17:35 UTC, marcodotcastro commented on app/models/weight_table.rb
> +  validate :validate_question_answer_structure
Use a chamada de custom validation

2024-07-09 17:35 UTC, Pjmaciel approved these changes
Codigo bem estruturado, nada a adicionar, parabens pelo trabalho.

2024-07-09 17:36 UTC, marcodotcastro commented on spec/models/weight_table_spec.rb
> +      json_data = '{"pergunta1": {"resposta1": 10, "resposta2": 5}}'
O dado não será uma string e sim um hash. Altere o teste

2024-07-09 17:36 UTC, marcodotcastro commented on spec/models/weight_table_spec.rb
O dado não será uma string e sim um hash. Altere o teste

2024-07-09 17:37 UTC, marcodotcastro commented on app/validators/weight_validator.rb
> +  def self.valid_structure?(json_data)
O dado não será uma string e sim um hash

2024-07-09 17:38 UTC, marcodotcastro commented on spec/models/weight_table_spec.rb
> +RSpec.describe WeightValidator do
É pra testar o model e não o validator

2024-07-09 17:39 UTC, marcodotcastro commented on app/validators/weight_validator.rb
> +class WeightValidator
Não é assim que cria um validator

2024-07-09 17:39 UTC, marcodotcastro requested changes
A lógica é funcionando e teste está quase correto, só falta organizar a estrutura do rails para a validação.

2024-07-11 16:51 UTC, ReginaTR commented on app/models/weight_table.rb
> +  validate :validate_question_answer_structure
Realizado.

2024-07-11 16:56 UTC, ReginaTR commented on spec/models/weight_table_spec.rb
> +RSpec.describe WeightValidator do
Realizado.

2024-07-11 16:56 UTC, ReginaTR commented on app/validators/weight_validator.rb
> +class WeightValidator
Corrigido.

2024-07-12 13:09 UTC, Pjmaciel approved these changes

2024-07-12 13:09 UTC, Pjmaciel commented on app/validators/weight_validator.rb
Retirar os comentarios.

2024-07-12 17:17 UTC, marcodotcastro approved these changes
Parabéns

2024-07-12 22:14 UTC, merged