Feature/54 criar interface de adio edio remoo visualizao e gerenciamento de webhooks
desenvolvendo-me/lead-score pull request #62
Opened 2024-07-23 16:48 UTC by mosca06

2024-07-25 18:31 UTC, Pjmaciel requested changes
Verifique as alteraçoes propostas.

2024-07-25 18:31 UTC, Pjmaciel commented on spec/controllers/webhooks/lead_transmission_controller_spec.rb
Retire os comentarios

2024-07-25 18:31 UTC, Pjmaciel commented on spec/factories/lead_transmissions.rb
Não seria melhor colocar valores mais proximos dos reais?

2024-07-25 18:31 UTC, Pjmaciel commented on spec/helpers/webhooks/lead_transmissions_helper_spec.rb
Retire caso nao for usar o helper.

2024-07-25 18:31 UTC, Pjmaciel commented on spec/models/lead_transmission_spec.rb
Seria melhor deixar os valores mais proximos do real.

2024-07-25 18:31 UTC, Pjmaciel commented on spec/views/webhooks/crud_lead_transmission_spec.rb
Remova os comentarios.

2024-07-25 18:57 UTC, mosca06 commented on spec/factories/lead_transmissions.rb
Alterado

2024-07-25 18:57 UTC, mosca06 commented on spec/helpers/webhooks/lead_transmissions_helper_spec.rb
excluido

2024-07-25 18:57 UTC, mosca06 commented on spec/models/lead_transmission_spec.rb
alterado

2024-07-25 18:57 UTC, mosca06 commented on spec/views/webhooks/crud_lead_transmission_spec.rb
removido

2024-07-30 19:26 UTC, Pjmaciel approved these changes

2024-07-31 12:10 UTC, Pjmaciel approved these changes

2024-08-05 12:20 UTC, ReginaTR approved these changes

2024-08-05 12:25 UTC, mosca06 commented on app/models/answer.rb
O nome dela foi alterada em outro commit e quando rodamos a migrate ele muda, assim que a alteraçao entrar na release deve parar de acontecer essa mudança.

2024-08-06 12:15 UTC, alinecintracamargo approved these changes

2024-09-06 21:34 UTC, cassiosantana commented on app/controllers/webhooks/lead_transmissions_controller.rb
Adicionar I18n.

2024-09-06 21:34 UTC, cassiosantana commented on app/views/shared/_nav_links.html.erb
- O controller de LeadTransmission já impede acesso não autenticado. Existe a necessidade de ocultar o link caso não logado?
- Adicionar I18n

2024-09-06 21:34 UTC, cassiosantana commented on app/views/webhooks/lead_transmissions/_form.html.erb
- Adicionar I18n

2024-09-06 21:34 UTC, cassiosantana commented on app/views/webhooks/lead_transmissions/_lead_transmission.html.erb
- Adicionar I18n

2024-09-06 21:34 UTC, cassiosantana commented on app/views/webhooks/lead_transmissions/edit.html.erb
- Adicionar I18n

2024-09-06 21:34 UTC, cassiosantana commented on app/views/webhooks/lead_transmissions/index.html.erb
- Adicionar I18n

2024-09-06 21:34 UTC, cassiosantana commented on app/views/webhooks/lead_transmissions/new.html.erb
- Adicionar I18n

2024-09-06 21:34 UTC, cassiosantana commented on app/views/webhooks/lead_transmissions/show.html.erb
- Adicionar I18n

2024-09-06 21:34 UTC, cassiosantana commented on config/routes.rb
De acordo com a descrição da tarefa essa gestão devem ser feitas pelo administrador. Acredito que devem estar na seção `manager` do sistema.

2024-09-06 21:34 UTC, cassiosantana commented on app/views/webhooks/lead_transmissions/show.html.erb
> +
Remover espaços adicionais.

2024-09-06 21:34 UTC, cassiosantana commented on spec/views/webhooks/crud_lead_transmission_spec.rb
O teste realizado é de feature mas está na camada de testes de views e com a nomenclatura incomum.

2024-09-09 22:02 UTC, devgustavoaprigio approved these changes

2024-09-09 22:08 UTC, devgustavoaprigio approved these changes

2024-09-15 23:05 UTC, merged