Feature/feature/15 implementar crud
desenvolvendo-me/lead-score pull request #63
Opened 2024-07-24 14:53 UTC by ReginaTR

Realizado as alterações do meu código e desfeito as alterações e remoções feitas no código dos colegas através de comando incorreto do git.

2024-07-24 21:12 UTC, marcodotcastro commented on app/controllers/weights_controller.rb
> +        format.html { redirect_to @weight, notice: 'Weight was successfully created.'}
Mova os notices para o I18n

2024-07-24 21:13 UTC, marcodotcastro requested changes
Acredito que é a última alteração

2024-07-25 18:21 UTC, marcodotcastro commented on app/models/client.rb
Esse código está com problema

2024-07-25 18:22 UTC, marcodotcastro commented on app/views/weights/_weight.html.erb
> +    Description
Use i18n para a descrição do atributos da tabela

2024-07-25 18:23 UTC, marcodotcastro commented on app/views/weights/edit.html.erb
> +          <%= link_to "Weights", weights_path, class: "hover:underline hover:text-slate-600 dark:hover:text-slate-400" %>
I18n para descrição

2024-07-25 18:23 UTC, marcodotcastro commented on app/views/weights/edit.html.erb
> +          <span class="text-primary-600 dark:text-primary-500" aria-current="page">Edit</span>
I18n para descrição

2024-07-25 18:24 UTC, marcodotcastro commented on app/views/weights/edit.html.erb
Use I18n para descrições links e buttons

2024-07-25 18:24 UTC, marcodotcastro commented on app/views/weights/new.html.erb
Use I18n para descrições links e buttons

2024-07-25 18:25 UTC, marcodotcastro commented on app/views/weights/show.html.erb
Use I18n para descrições links e buttons

2024-07-25 18:27 UTC, marcodotcastro commented on app/controllers/weights_controller.rb
> +        format.html { redirect_to @weight, notice: I18n.t('notice.create', model:'Weight')}
Leia sobre i18n lazy-lookup,  https://guides.rubyonrails.org/i18n.html#lazy-lookup

2024-07-25 18:27 UTC, marcodotcastro commented on app/controllers/weights_controller.rb
Leia sobre i18n lazy-lookup, https://guides.rubyonrails.org/i18n.html#lazy-lookup

2024-07-25 18:27 UTC, marcodotcastro requested changes
Agora são os últimos ajustes

2024-07-25 18:36 UTC, ReginaTR commented on app/controllers/weights_controller.rb
> +        format.html { redirect_to @weight, notice: 'Weight was successfully created.'}
Movido.

2024-07-25 18:40 UTC, Pjmaciel approved these changes

2024-07-25 19:11 UTC, ReginaTR commented on app/views/weights/_weight.html.erb
> +    Description
Realizado

2024-07-25 19:30 UTC, ReginaTR commented on app/views/weights/edit.html.erb
Realizado

2024-07-25 23:07 UTC, ReginaTR commented on app/views/weights/new.html.erb
Realizado

2024-07-25 23:11 UTC, ReginaTR commented on app/views/weights/show.html.erb
Realizado

2024-07-25 23:14 UTC, ReginaTR commented on app/views/weights/index.html.erb
Realizado

2024-07-25 23:21 UTC, ReginaTR commented on app/models/client.rb
Resolvido

2024-07-26 18:55 UTC, marcodotcastro approved these changes

2024-07-30 19:47 UTC, merged